/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlbumCard: typeof import('./src/components/publicComponents/AlbumCard.vue')['default']
    ArtistCard: typeof import('./src/components/publicComponents/ArtistCard.vue')['default']
    CollectDialogs: typeof import('./src/components/publicComponents/CollectDialogs.vue')['default']
    Comment: typeof import('./src/components/publicComponents/Comment.vue')['default']
    CurrentPlay: typeof import('./src/components/panel/components/CurrentPlay.vue')['default']
    DeskLyric: typeof import('./src/components/publicComponents/DeskLyric.vue')['default']
    Frequency: typeof import('./src/components/playPage/Frequency.vue')['default']
    Local: typeof import('./src/components/setting/Local.vue')['default']
    LocalOption: typeof import('./src/components/panel/components/LocalOption.vue')['default']
    LoginWYYDialogs: typeof import('./src/components/publicComponents/LoginWYYDialogs.vue')['default']
    Lyric: typeof import('./src/components/playPage/Lyric.vue')['default']
    Menu: typeof import('./src/components/navigator/components/Menu.vue')['default']
    MiniLyric: typeof import('./src/components/panel/components/MiniLyric.vue')['default']
    NavBar: typeof import('./src/components/navigator/NavBar.vue')['default']
    NetEaseCloud: typeof import('./src/components/setting/NetEaseCloud.vue')['default']
    NewPlaylistDialogs: typeof import('./src/components/publicComponents/NewPlaylistDialogs.vue')['default']
    Other: typeof import('./src/components/setting/Other.vue')['default']
    Panel: typeof import('./src/components/panel/Panel.vue')['default']
    PlayBar: typeof import('./src/components/player/PlayBar.vue')['default']
    PlayBtn: typeof import('./src/components/player/components/PlayBtn.vue')['default']
    PlaylistCard: typeof import('./src/components/publicComponents/PlaylistCard.vue')['default']
    ProgressLinear: typeof import('./src/components/player/components/ProgressLinear.vue')['default']
    RecentPlay: typeof import('./src/components/panel/components/RecentPlay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchAlbumDialogs: typeof import('./src/components/publicComponents/SearchAlbumDialogs.vue')['default']
    SearchArtistDialogs: typeof import('./src/components/publicComponents/SearchArtistDialogs.vue')['default']
    SearchSuggest: typeof import('./src/components/navigator/components/SearchSuggest.vue')['default']
    SearchTrackDialogs: typeof import('./src/components/publicComponents/SearchTrackDialogs.vue')['default']
    ShowModel: typeof import('./src/components/playPage/ShowModel.vue')['default']
    SongCard: typeof import('./src/components/publicComponents/SongCard.vue')['default']
    SongControl: typeof import('./src/components/playPage/SongControl.vue')['default']
    SongInfos: typeof import('./src/components/player/components/SongInfos.vue')['default']
    Theme: typeof import('./src/components/setting/Theme.vue')['default']
    ThemeSelectDialogs: typeof import('./src/components/publicComponents/ThemeSelectDialogs.vue')['default']
    Tip: typeof import('./src/components/publicComponents/Tip.vue')['default']
    Tips: typeof import('./src/components/publicComponents/Tips.vue')['default']
    UserDialogs: typeof import('./src/components/navigator/components/UserDialogs.vue')['default']
    UserPlaylist: typeof import('./src/components/panel/components/UserPlaylist.vue')['default']
    VolumeBar: typeof import('./src/components/player/components/VolumeBar.vue')['default']
  }
}
